FROM  node:21.0.0-alpine

# Set the working directory in the container
WORKDIR /root/

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install project dependencies
RUN npm install

# Copy the rest of your project files to the working directory
COPY . .