version: '3'
services:
  frontend:
    container_name: docker-frontend
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    command: npm start
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: sync
          path: ./client/src
          target: /root/src
          ignore:
            - node_modules/
    stdin_open: true
    tty: true
    depends_on:
      - golang
    restart: unless-stopped

  nginx:
    image: nginx:stable-alpine
    container_name: docker-nginx
    ports:
      - "8000:8000"
    volumes:
      - ./nginx/nginx.conf.dev:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - frontend

  golang:
    container_name: golang
    ports:
      - "8080:8080"
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /etc/ssl/certs:/etc/ssl/certs 

