version: '3.8'

services:

  postgres:
    container_name: postgres
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: poker
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql_data:/docker-entrypoint-initdb.d
  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./client:/app
      - /app/node_modules

  server:
    build: ./server
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=mydatabase
      - DB_PORT=5432
    volumes:
      - ./server:/app

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - client
      - server
  
volumes:
  postgres_data: