services:
  client:
    container_name: client
    build: ./client
    ports:
      - "3000:80"  # Пробрасываем порт 3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./client:/app
      - /app/node_modules

volumes:
  postgres_data: