services:
  postgres:
    container_name: postgres
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: poker
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql_data:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d poker" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  client:
    container_name: client
    build: ./client
    ports:
      - "3000:3000"  # Пробрасываем порт 3000
    depends_on:
      - server
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - app-network

  server:
    container_name: server
    build: ./server
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/poker
    volumes:
      - ./server:/app
    networks:
      - app-network

  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - client
      - server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: