// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc_repository

type Comment struct {
	CommentID int64
	PokerID   string
	UserID    int64
	TaskID    int64
	Text      string
}

type User struct {
	UserID             int64
	Name               string
	EvaluationStrategy *string
	MaximumScore       *int32
}

type UserAuthProvider struct {
	UserID      int64
	ProviderUid string
	Provider    string
	Name        *string
}

type UserSetting struct {
	UserID             int64
	EvaluationStrategy string
	MaximumScore       int32
}
