// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc_repository

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, name string) (int32, error)
}

var _ Querier = (*Queries)(nil)
