// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package sqlc_repository

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (name)
VALUES ($1)
returning user_id
`

func (q *Queries) CreateUser(ctx context.Context, name string) (int32, error) {
	row := q.db.QueryRow(ctx, createUser, name)
	var user_id int32
	err := row.Scan(&user_id)
	return user_id, err
}
